name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        test-type: [test, coverage]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}-${{ matrix.test-type }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm install
        if [ "${{ matrix.test-type }}" = "test" ]; then
          npm test
        else
          npm run ${{ matrix.test-type }}
        fi  
        
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ./coverage/lcov.info
      if: matrix.test-type == coverage
      env:
        CI: true
